### ISSUE TITLE
Request for raw nanopore cDNA fast5 files

### ISSUE THREAD

**Issue by CrazyHsu** [liu3zhenlab/A188Ref1#2]
Hi,

I have read the paper you put in biorxiv [Chromosome-level Genome Assembly of a Regenerable Maize Inbred Line A188](https://www.biorxiv.org/content/10.1101/2020.09.09.289611v1.full), and I want to some research in poly-A length in maize with raw nanopore cDNA fast5 files. But there is no fast5 file in ncbi accession PRJNA635654 when I looked into it, can you share the raw fast5 files? Any help will be appreciated! Thanks!

Feng

**Comment by liu3zhenlab** [comment]
We have submitted fastq data. You can try that first. We will figure out how to share the larger fast5 data.

**Comment by CrazyHsu** [comment]
Hi Dr. Liu,

Thanks for your prompt reply.
I have tried the fastq data with nanopolish, but it seems that nanopolish need fast5 files to build index and then get poly-A length(https://nanopolish.readthedocs.io/en/latest/quickstart_polya.html#segmentation-and-tail-length-estimation-with-nanopolish-polya). 
There is another solution mentioned in https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-transcriptome/phase1_analyses.md, that you can share the index like http://s3.amazonaws.com/nanopore-human-wgs/rna/phase1_analyses/rnaconsort.npolish.idx.zip, for us to avoid time-costing base calling and we can also run the poly-A length analysis, if you used nanopolish to get final fastq file.

And NCBI now supports uploading raw fast5 format files as I know. There is a example https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12822922:
![image](https://user-images.githubusercontent.com/20716042/104979152-8aea1180-5a3e-11eb-8b6b-6318075a5b58.png)
Thank you again for replying. Any help will be greatly appreciated!

Cheers,
Feng

**Comment by CrazyHsu** [comment]
Hi, Dr. Liu,

Sorry to bother you again. You have done a very nice work in constructing a chromosome-level genome assembly of A188 and then found the key point that accounts for the white seed phenotype of A188. Besides, with the help of transcriptome and epigenome analyses, you have also uncover the DNA methylation and gene expression patterns in callus. 
However, you have only used the nanopore data to measure the methylation. As I know, polyA-length have been known to be one of the key factors regulating RNA stability and translational efficiency which is rarely studied in maize owing to the limitation of technical methods. But But with the rapid development of nanopore direct sequencing, it can be easily measured. Have you ever considered doing some researches on this? Because of the technology relatively expensive, there aren't many publicly Fast5 files available for download and secondary analysis. I'm also stuck by the lacking of the resources, can you please share the Fast5 files or indexed files using nanopolish? 
Thank you for your attention to this matter, any help will be greatly appreciated.

Feng

**Comment by liu3zhenlab** [comment]
Hi Feng,

We don't have a resource to host such data online for regular downloading. Could you send me (liu3zhen@ksu.edu) an email and we will send you a link that temporarily host the data. We did not use Nanopolish to polish reads. The tool was only used for correcting assembled genomic contigs.

-Sanzhen
